<?xml version="1.0"?>
<package format="3">
  <name>rslidar_sdk</name>
  <version>1.5.20</version>
  <description>The rslidar_sdk package</description>
  <maintainer email="orion.he@robosense.cn">robosense</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>
  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>libpcap</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>rslidar_msg</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>yaml-cpp</depend>
  <depend>ament_index_cpp</depend>

  <export>
     <build_type>ament_cmake</build_type>
  </export>
</package>
